version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: connectfy/client-dev
    container_name: client-dev
    ports:
      - "4800:4800"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0
    command: npm run dev
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
