version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: connectfy/connectfy-client-prod
    container_name: connectfy-client-prod
    ports:
      - "4800:4800"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
