services:
  client:
    image: connectfy/connectfy-client-prod:1.0.0
    ports:
      - "4800:4800"
    networks:
      - connectfy-client-network
    restart: always
    env_file:
      - .env.production
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  connectfy-client-network:
    driver: bridge