import { ICountry } from "@/types/auth/auth/auth.type";

export const COUNTRIES: ICountry[] = [
  {
    key: "az",
    name: "azerbaijan",
    flag: "fi fi-az",
    code: "+994",
    numberLength: 9,
  },
  {
    key: "tr",
    name: "türkiye",
    flag: "fi fi-tr",
    code: "+90",
    numberLength: 10,
  },
  { key: "ru", name: "russia", flag: "fi fi-ru", code: "+7", numberLength: 10 },
  { key: "us", name: "usa", flag: "fi fi-us", code: "+1", numberLength: 10 },
  { key: "gb", name: "uk", flag: "fi fi-gb", code: "+44", numberLength: 10 },
  {
    key: "de",
    name: "germany",
    flag: "fi fi-de",
    code: "+49",
    numberLength: 10,
  },
  { key: "fr", name: "france", flag: "fi fi-fr", code: "+33", numberLength: 9 },
  { key: "es", name: "spain", flag: "fi fi-es", code: "+34", numberLength: 9 },
  { key: "it", name: "italy", flag: "fi fi-it", code: "+39", numberLength: 10 },
  { key: "cn", name: "china", flag: "fi fi-cn", code: "+86", numberLength: 11 },
  { key: "jp", name: "japan", flag: "fi fi-jp", code: "+81", numberLength: 10 },
  {
    key: "kr",
    name: "south_korea",
    flag: "fi fi-kr",
    code: "+82",
    numberLength: 10,
  },
  {
    key: "ua",
    name: "ukraine",
    flag: "fi fi-ua",
    code: "+380",
    numberLength: 9,
  },
  {
    key: "ge",
    name: "georgia",
    flag: "fi fi-ge",
    code: "+995",
    numberLength: 9,
  },
  { key: "ir", name: "iran", flag: "fi fi-ir", code: "+98", numberLength: 10 },
  { key: "in", name: "india", flag: "fi fi-in", code: "+91", numberLength: 10 },
  { key: "ca", name: "canada", flag: "fi fi-ca", code: "+1", numberLength: 10 },
  {
    key: "kz",
    name: "kazakhstan",
    flag: "fi fi-kz",
    code: "+7",
    numberLength: 10,
  },
  {
    key: "uz",
    name: "uzbekistan",
    flag: "fi fi-uz",
    code: "+998",
    numberLength: 9,
  },
  { key: "ae", name: "uae", flag: "fi fi-ae", code: "+971", numberLength: 9 },
];
