import { ICountry } from "../interfaces/interfaces";

export const COUNTRIES: ICountry[] = [
  {
    key: "az",
    name: "azerbaijan",
    flag: "fi fi-az",
    code: "+994",
    numberLength: 9,
    totalLength: 12,
    format: "00 000 00 00",
  },
  {
    key: "tr",
    name: "türkiye",
    flag: "fi fi-tr",
    code: "+90",
    numberLength: 10,
    totalLength: 13,
    format: "000 000 00 00",
  },
  {
    key: "ru",
    name: "russia",
    flag: "fi fi-ru",
    code: "+7",
    numberLength: 10,
    totalLength: 13,
    format: "000 000 00 00",
  },
  {
    key: "us",
    name: "usa",
    flag: "fi fi-us",
    code: "+1",
    numberLength: 10,
    totalLength: 12,
    format: "000 000 0000",
  },
  {
    key: "gb",
    name: "uk",
    flag: "fi fi-gb",
    code: "+44",
    numberLength: 10,
    totalLength: 12,
    format: "0000 000 000",
  },
  {
    key: "de",
    name: "germany",
    flag: "fi fi-de",
    code: "+49",
    numberLength: 10,
    totalLength: 11,
    format: "000 0000000",
  },
  {
    key: "fr",
    name: "france",
    flag: "fi fi-fr",
    code: "+33",
    numberLength: 9,
    totalLength: 13, // "0 00 00 00 00"
    format: "0 00 00 00 00",
  },
  {
    key: "es",
    name: "spain",
    flag: "fi fi-es",
    code: "+34",
    numberLength: 9,
    totalLength: 11,
    format: "000 000 000",
  },
  {
    key: "it",
    name: "italy",
    flag: "fi fi-it",
    code: "+39",
    numberLength: 10,
    totalLength: 12,
    format: "000 000 0000",
  },
  {
    key: "cn",
    name: "china",
    flag: "fi fi-cn",
    code: "+86",
    numberLength: 11,
    totalLength: 13,
    format: "000 0000 0000",
  },
  {
    key: "jp",
    name: "japan",
    flag: "fi fi-jp",
    code: "+81",
    numberLength: 10,
    totalLength: 12,
    format: "00 0000 0000",
  },
  {
    key: "kr",
    name: "south_korea",
    flag: "fi fi-kr",
    code: "+82",
    numberLength: 10,
    totalLength: 12,
    format: "00 0000 0000",
  },
  {
    key: "ua",
    name: "ukraine",
    flag: "fi fi-ua",
    code: "+380",
    numberLength: 9,
    totalLength: 12,
    format: "00 000 00 00",
  },
  {
    key: "ge",
    name: "georgia",
    flag: "fi fi-ge",
    code: "+995",
    numberLength: 9,
    totalLength: 12,
    format: "000 00 00 00",
  },
  {
    key: "ir",
    name: "iran",
    flag: "fi fi-ir",
    code: "+98",
    numberLength: 10,
    totalLength: 12,
    format: "000 000 0000",
  },
  {
    key: "in",
    name: "india",
    flag: "fi fi-in",
    code: "+91",
    numberLength: 10,
    totalLength: 11,
    format: "00000 00000",
  },
  {
    key: "ca",
    name: "canada",
    flag: "fi fi-ca",
    code: "+1",
    numberLength: 10,
    totalLength: 12,
    format: "000 000 0000",
  },
  {
    key: "kz",
    name: "kazakhstan",
    flag: "fi fi-kz",
    code: "+7",
    numberLength: 10,
    totalLength: 13,
    format: "000 000 00 00",
  },
  {
    key: "uz",
    name: "uzbekistan",
    flag: "fi fi-uz",
    code: "+998",
    numberLength: 9,
    totalLength: 12,
    format: "00 000 00 00",
  },
  {
    key: "ae",
    name: "uae",
    flag: "fi fi-ae",
    code: "+971",
    numberLength: 9,
    totalLength: 11,
    format: "0 000 0000",
  },
];
